import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { StarknetProvider } from "../app/components/starknet-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StarknetProvider>
        <body className="relative w-full bg-main-bg bg-cover bg-center bg-no-repeat pt-[120px]">
          <Navbar />
          {children}
        </body>
      </StarknetProvider>
    </html>
  );
}
